### ISSUE TITLE
configurable project boards

### ISSUE THREAD

**Issue by colevandersWands** [school-as-code-testing/school-as-code#1]
@lpmi-13, can [this line](https://github.com/school-as-code-testing/school-as-code/blob/9fb86e6a5380ea9536839a9dab8fd1a16d998009/create_projects.sh#L3) eventually read a list of boards from `school.yml`?

**Comment by lpmi-13** [comment]
So we _can_ use yaml with shell scripts, but it's arcane AF (https://gist.github.com/pkuczynski/8665367). This will be part of the design doc discussion, since this is one of the arguments for switching to use a python or node wrapper to the github api.

**Comment by colevandersWands** [comment]
I'm up for writing our own yaml parser in bash if you are, it would lay a good foundation and I'd rather not gather technical debt this early in the project.

**Comment by lpmi-13** [comment]
just to close this out, we're going to use yaml, cause it's simple and human/machine readable, and most likely we'll be using node to interact with the github API anyway, so there's no need to do any funky yaml parsing in shell scripts.
