### ISSUE TITLE
investigate if we can create issues first, then create cards that are linked to issues

### ISSUE THREAD

**Issue by lpmi-13** [school-as-code-testing/school-as-code#11]
So I just happened to stumble across this documentation for Octokit, and it looks like the params that can be expected in the call to create a card actually CAN be used to link it to an existing issue!

https://www.rubydoc.info/gems/octokit/Octokit%2FClient%2FProjects:create_project_card

`@client.create_project_card(123495, content_id: 1, content_type: 'Issue')`

The github api docs do mention both `content_id` and `content_type`, but then proceed to give zero examples or even enumerate what the possible values are or what they relate to.

**Comment by colevandersWands** [comment]
I think we have a disconnect here.  I was thinking there would be no cards, only issues moved to the board.  this has the advantage of fewer things and of using issue templates for everything.  let's take this conversation to #8 with the bigger thoughts about issues? it's also relevant to #9

if we go the all-issues route than the api limitations for cards won't matter. and it looks like moving issues to project boards shouldn't be bad if we wanted to automate that - https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards

**Comment by lpmi-13** [comment]
So just to clarify (I should have been more explicit earlier), I'll explain a bit more about what I mean. When I use the term "cards", I'm basically meaning "the things you can move around on boards like trello/jira/github projects. Github also refers to "cards" in their API docs/endpoints, which roughly maps to the same thing (things you can drag around on the project board UI).
https://docs.github.com/en/rest/reference/projects#cards

It's unfortunate that you can create a "card" via the api that is basically just a note...which we definitely don't want.

I wasn't aware that the cards on the project boards I was looking at for the lab-antwerp board started their lives as issues, and then later got put onto the project boards, so yes, as you mentioned, we'll start with issue and move those to the boards.

**Comment by lpmi-13** [comment]
and then for "template issues", I assume that'll just be a case of specifying default labels/assignee/etc that we can use when we call the API.

**Comment by colevandersWands** [comment]
You can already set default labels and milestones within the template's markdown, then variable labels or assignees could be set by the API.

**Comment by lpmi-13** [comment]
To be discussed in general:

The ratio/breakdown of config that lives in the repo template vs the config that lives in the yml

**Comment by lpmi-13** [comment]
This will be addressed when we discuss where the "config" lives, and for our MVP, keeping the stuff in the template is probably the easiest.
